## MSRS Abstract Sorting 2021
---

In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [18]:
import pandas as pd
import os 
import sys
import csv
import numpy as np

## Assign random IDs to students

In [66]:
students = pd.read_excel('data/students.xlsx')
students.head()

,Timestamp,Name,Email,Year,MD/PhD student?,Mentor,Research Department Affiliation,Scholarly Concentration,Title,Authors,Background:,Methods:,Results:,Conclusion:,Research Funding Mechanism:,"Does the above format (background, methods, results, conclusion) NOT apply to your abstract?",Please enter your abstract text below. (300 word limit),Are you interested in being considered for an oral or podium presentation?
0,2020-10-16 14:51:03.068,Test,Test,MS 1,Yes,Test,Test,Clinical Science,Test,Test,Test,Test,Test,Test,Test,"No, it doesn't apply",Test,NaN
1,2020-10-17 12:32:33.197,Natalie Marrero,nmarrer1@jhmi.edu,MS 2,No,"Rani Hasan, MD",Interventional Cardiology,Public Health,Readmission after Transcatheter Aortic Valve R...,"Natalie Marrero BA, Jacqueline Latina, MD, Rim...",Transcatheter Aortic Valve Replacement (TAVR) ...,We conducted a narrative review of the literat...,"A total of 54 studies of 514,353 patients, inc...","Overall, most readmissions are non-cardiac in ...",Deans Funding,"Yes, it applies",NaN,Yes
2,2020-10-20 15:47:01.479,Matthew Rabinowitz,mrabino6@jhmi.edu,MS 2,No,"Amin Herati, MD",Department of Urology,Clinical Science,The Impact of Telemedicine on Access to Urolog...,"Matthew J. Rabinowitz BS, Chad Ellimoottil MD,...",COVID-19 has ushered in telemedicine at a hist...,"An IRB-approved, retrospective analysis was pe...",Total outpatient encounters were reduced by 65...,Our findings suggest that outpatients who are ...,Deans Funding; Persky Summer Research Scholarship,"Yes, it applies",NaN,Yes
3,2020-10-21 10:02:18.190,Michael Bray,mbray11@jhmi.edu,MS 3,No,Paul Nestadt,Department of Psychiatry and Behavioral Sciences,Clinical Science,Racial Differences in Suicide Mortality During...,"Michael JC Bray MS, Nicholas O Daneshvari BA, ...",Background: Changing patterns of suicidality d...,Methods: State-wide data for all non-natural d...,Results: Suicide mortality increased among Bla...,"Conclusion: During the COVID-19 pandemic, suic...",Not funded,"Yes, it applies",NaN,Yes
4,2020-10-30 12:27:55.414,Palak Patel,ppatel96@jhmi.edu,MS 2,No,"Daniel Rhee, MD MPH",Department of Pediatric Surgical Oncology,Clinical Science,Appendectomy and cholecystectomy outcomes for ...,"Palak P. Patel B.S., Jennine H. Weller M.D., C...",Children undergoing cancer treatment often dev...,This was a retrospective cohort study of pedia...,A total of 328 children met inclusion criteria...,"In children with active cancer, leukopenia was...",Deans Funding,"Yes, it applies",NaN,Yes

In [67]:
rng = np.random.default_rng()
ids = rng.choice(np.arange(100, 999), size=len(students), replace=False)
students['ids'] = ids
print(ids)
students.head()

[702 651 292 813 739 837 611 672 235 276 290 417 376 500 744 819 257 230
 930 106 630 687 526 350 198 411 926 838 714 488 927 299 422 210 827 814
 110 541 664 612 343 225 783 593 847 554 108 585 543 991 718 742 193 661
 830 392 576 810 788 443 974 851 189 935 429 629 511 874 315 344 848 378
 412 806 196 760 992 274 949 416 211 804 377 743 617 816 584 126 741 520
 678 314 792 832 653 598 834 219 928 984 959 916 471 770 562]

,Timestamp,Name,Email,Year,MD/PhD student?,Mentor,Research Department Affiliation,Scholarly Concentration,Title,Authors,Background:,Methods:,Results:,Conclusion:,Research Funding Mechanism:,"Does the above format (background, methods, results, conclusion) NOT apply to your abstract?",Please enter your abstract text below. (300 word limit),Are you interested in being considered for an oral or podium presentation?,ids
0,2020-10-16 14:51:03.068,Test,Test,MS 1,Yes,Test,Test,Clinical Science,Test,Test,Test,Test,Test,Test,Test,"No, it doesn't apply",Test,NaN,702
1,2020-10-17 12:32:33.197,Natalie Marrero,nmarrer1@jhmi.edu,MS 2,No,"Rani Hasan, MD",Interventional Cardiology,Public Health,Readmission after Transcatheter Aortic Valve R...,"Natalie Marrero BA, Jacqueline Latina, MD, Rim...",Transcatheter Aortic Valve Replacement (TAVR) ...,We conducted a narrative review of the literat...,"A total of 54 studies of 514,353 patients, inc...","Overall, most readmissions are non-cardiac in ...",Deans Funding,"Yes, it applies",NaN,Yes,651
2,2020-10-20 15:47:01.479,Matthew Rabinowitz,mrabino6@jhmi.edu,MS 2,No,"Amin Herati, MD",Department of Urology,Clinical Science,The Impact of Telemedicine on Access to Urolog...,"Matthew J. Rabinowitz BS, Chad Ellimoottil MD,...",COVID-19 has ushered in telemedicine at a hist...,"An IRB-approved, retrospective analysis was pe...",Total outpatient encounters were reduced by 65...,Our findings suggest that outpatients who are ...,Deans Funding; Persky Summer Research Scholarship,"Yes, it applies",NaN,Yes,292
3,2020-10-21 10:02:18.190,Michael Bray,mbray11@jhmi.edu,MS 3,No,Paul Nestadt,Department of Psychiatry and Behavioral Sciences,Clinical Science,Racial Differences in Suicide Mortality During...,"Michael JC Bray MS, Nicholas O Daneshvari BA, ...",Background: Changing patterns of suicidality d...,Methods: State-wide data for all non-natural d...,Results: Suicide mortality increased among Bla...,"Conclusion: During the COVID-19 pandemic, suic...",Not funded,"Yes, it applies",NaN,Yes,813
4,2020-10-30 12:27:55.414,Palak Patel,ppatel96@jhmi.edu,MS 2,No,"Daniel Rhee, MD MPH",Department of Pediatric Surgical Oncology,Clinical Science,Appendectomy and cholecystectomy outcomes for ...,"Palak P. Patel B.S., Jennine H. Weller M.D., C...",Children undergoing cancer treatment often dev...,This was a retrospective cohort study of pedia...,A total of 328 children met inclusion criteria...,"In children with active cancer, leukopenia was...",Deans Funding,"Yes, it applies",NaN,Yes,739

## Process faculty

Preview and confirm judge sheet. Make sure to specify the correct sheet and header row from the excel file.

Drop the columns that are no longer necessary for the sorting process.

In [57]:
judges = pd.read_excel('data/judges2.xlsx', sheet_name="Sheet3", header=3)

judges.drop(columns=[
    'Basic Science', 
    'Clinical Science', 
    'Public Health', 
    'Ethics and the Art of Medicine', 
    'History of Medicine', 
    'Justification / Notes', 
    'signed up for only 1 category', 
    'What activities would you like to judge at MSRS 2021? ',
    "What topic would you like to judge? If you are interested in multiple options, you'll be placed in whatever topic needs more judges. ",
    'Timestamp',
    "Would you like to recommend any colleagues who may be interested in judging? If so, please let us know their name(s) and affiliation(s). "
], inplace=True)

judges.head()

,Email Address,First Name,Last Name,Would you like to judge student abstracts?,Assignment
0,mbraitr1@jhmi.edu,Mariana,Brait,Yes,Basic Science
1,chute@jhu.edu,Christopher,Chute,No,Public Health
2,Mark.Anderson@jhmi.edu,Mark,Anderson,Yes,Basic Science
3,jcoulte4@jhmi.edu,Jonathan,Coulter,Yes,Public Health
4,mfissell@jhu.edu,Mary,Fissell,Yes,History of Medicine

Observe the columns that remain. Select the columns that will be retained in the output sheet

In [58]:
judges.columns

Index(['Email Address', 'First Name', 'Last Name',
       'Would you like to judge student abstracts?', 'Assignment'],
      dtype='object')

In [60]:
output_cols = ['Email Address', 'First Name', 'Last Name',]

### Begin to separate the judges for the 5 categories into 5 data frame slices

In [61]:
judges_basic = judges.loc[(judges["Would you like to judge student abstracts?"] == "Yes") & (judges["Assignment"] == "Basic Science")][output_cols]

judges_basic.head()

             Email Address First Name        Last Name
0        mbraitr1@jhmi.edu    Mariana            Brait
2   Mark.Anderson@jhmi.edu       Mark         Anderson
8        mdiazbu1@jhmi.edu    Marcelo  Diaz Bustamante
10        kdavi140@jhu.edu        Kim            Davis
16       mhalush1@jhmi.edu       Marc         Halushka

In [62]:
judges_clinical = judges.loc[(judges["Would you like to judge student abstracts?"] == "Yes") & (judges["Assignment"] == "Clinical Science")][output_cols]

judges_clinical.head()

         Email Address First Name  Last Name
7   gdagnelie@jhmi.edu     Gislin   Dagnelie
9    dhackam1@jhmi.edu      David     Hackam
17      ebass@jhmi.edu       Eric       Bass
18   chicks11@jhmi.edu    Caitlin      Hicks
19   dgladst1@jhmi.edu    Douglas  Gladstone

In [63]:
judges_public = judges.loc[(judges["Would you like to judge student abstracts?"] == "Yes") & (judges["Assignment"] == "Public Health")][output_cols]

judges_public.head()

          Email Address First Name Last Name
3     jcoulte4@jhmi.edu   Jonathan   Coulter
12  brianhutler@jhu.edu      Brian    Hutler
13     rgurari1@jhu.edu     Rachel  Gur-Arie
22    plipsett@jhmi.edu     Pamela   Lipsett
28      hmckay4@jhu.edu    Heather     McKay

In [64]:
judges_HEART = judges.loc[(judges["Would you like to judge student abstracts?"] == "Yes") & (judges["Assignment"] == "Ethics and the Art of Medicine")][output_cols]

judges_HEART.head()

        Email Address      First Name  Last Name
14   agarlan3@jhu.edu          Andrew    Garland
63  MHANSON4@JHMI.EDU           MARTA     HANSON
66   jmurph46@jhu.edu            Juli  Bollinger
67   mcbeach@jhmi.edu  Mary Catherine      Beach
69      alanr@jhu.edu            Alan  Regenberg

In [76]:
judges_hist = judges.loc[(judges["Would you like to judge student abstracts?"] == "Yes") & (judges["Assignment"] == "History of Medicine")][output_cols]

judges_hist.head()

        Email Address      First Name Last Name
4    mfissell@jhu.edu            Mary   Fissell
5   gmooney3@jhmi.edu          Graham    Mooney
6    ruggere@jhmi.edu       Christine   Ruggere
31  rpackar2@jhmi.edu        Randall    Packard
80  lmartin7@jhmi.edu  Lorrin (David)    Martin

In [83]:
list(judges_hist.columns)

['Email Address', 'First Name', 'Last Name']

In [82]:
list(zip(judges_hist['First Name'],judges_hist['Last Name']))

[('Mary', 'Fissell'),
 ('Graham', 'Mooney'),
 ('Christine', 'Ruggere'),
 ('Randall ', 'Packard'),
 ('Lorrin (David)', 'Martin')]

In [70]:
judge_dict = {"%s %s"%(first.strip(), last.strip()):[] for first, last in judges_hist[['First Name', 'Last Name']]}

ValueError: too many values to unpack (expected 2)

In [93]:
import random
print(list(judges_clinical.keys()))

['Email Address', 'First Name', 'Last Name']

In [95]:
test = list(range(10))
random.shuffle(test)
print(test)

[0, 8, 5, 4, 2, 9, 7, 6, 1, 3]

In [96]:
[False]*4

[False, False, False, False]

In [88]:
list(map(str, ids))

['702',
 '651',
 '292',
 '813',
 '739',
 '837',
 '611',
 '672',
 '235',
 '276',
 '290',
 '417',
 '376',
 '500',
 '744',
 '819',
 '257',
 '230',
 '930',
 '106',
 '630',
 '687',
 '526',
 '350',
 '198',
 '411',
 '926',
 '838',
 '714',
 '488',
 '927',
 '299',
 '422',
 '210',
 '827',
 '814',
 '110',
 '541',
 '664',
 '612',
 '343',
 '225',
 '783',
 '593',
 '847',
 '554',
 '108',
 '585',
 '543',
 '991',
 '718',
 '742',
 '193',
 '661',
 '830',
 '392',
 '576',
 '810',
 '788',
 '443',
 '974',
 '851',
 '189',
 '935',
 '429',
 '629',
 '511',
 '874',
 '315',
 '344',
 '848',
 '378',
 '412',
 '806',
 '196',
 '760',
 '992',
 '274',
 '949',
 '416',
 '211',
 '804',
 '377',
 '743',
 '617',
 '816',
 '584',
 '126',
 '741',
 '520',
 '678',
 '314',
 '792',
 '832',
 '653',
 '598',
 '834',
 '219',
 '928',
 '984',
 '959',
 '916',
 '471',
 '770',
 '562']

In [90]:

for x in range(20):
    print(x)
    if x == 5: 
        break

0
1
2
3
4
5